name: BTC Analysis & Discord Alert

on:
  schedule:
    - cron: "0 23 * * *"  # Runs daily at 6:00 AM UTC+7 (23:00 UTC)
  workflow_dispatch:  # Allow manual trigger

jobs:
  btc_analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pandas requests

      - name: Fetch BTC Data
        run: |
          ls -lah  # 🔍 Debug: List all files to check if fetch_data.py exists
          pwd  # 🔍 Debug: Print the current working directory
          python fetch_data.py  # ✅ Corrected script name

      - name: Read & Log BTC Data
        run: cat btc_hourly_prices.csv  # Print CSV content for debugging

      - name: Run Analysis Script
        run: python analyze_data.py  # Sends BTC data to DeepSeek for AI analysis

      - name: Send to Discord
        run: python send_to_discord.py  # Sends results via Discord Webhook

      - name: Upload CSV as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: btc_data_log
          path: btc_hourly_prices.csv
